# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\player\ui\CiliCiliPlayerContainer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CiliCiliPlayer(object):
    def setupUi(self, CiliCiliPlayer):
        CiliCiliPlayer.setObjectName("CiliCiliPlayer")
        CiliCiliPlayer.resize(1620, 987)
        CiliCiliPlayer.setMinimumSize(QtCore.QSize(480, 270))
        CiliCiliPlayer.setStyleSheet("*{\n"
"background-color: rgba(0,0,0,0);\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(CiliCiliPlayer)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.retranslateUi(CiliCiliPlayer)
        QtCore.QMetaObject.connectSlotsByName(CiliCiliPlayer)

    def retranslateUi(self, CiliCiliPlayer):
        _translate = QtCore.QCoreApplication.translate
        CiliCiliPlayer.setWindowTitle(_translate("CiliCiliPlayer", "Form"))
