# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\player\ui\playControlBar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from PlayerAssets_rc import *
from .SeekSlider import SeekSlider


class PlayerControlBar(QtWidgets.QWidget):
    def __init__(self, *args, **kwargs):
        super(PlayerControlBar,self).__init__(*args, **kwargs)
        self.setupUi(self.parent())
        self.isEntry = False
        self.timerIsQuit =  False

    def enterEvent(self, event: QtCore.QEvent):
        self.isEntry = True
        return super().enterEvent(event)

    def leaveEvent(self, event: QtCore.QEvent):
        self.isEntry = False
        if self.timerIsQuit:
            self.hide()
        return super().leaveEvent(event)


    def setupUi(self, widget):
        self.playControlBar = QtWidgets.QFrame(widget)
        self.playControlBar.setGeometry(QtCore.QRect(90, 490, 957, 102))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.playControlBar.sizePolicy().hasHeightForWidth())
        self.playControlBar.setSizePolicy(sizePolicy)
        self.playControlBar.setMinimumSize(QtCore.QSize(0, 102))
        self.playControlBar.setMaximumSize(QtCore.QSize(16777215, 100))
        self.playControlBar.setStyleSheet("#playControlBar {\n"
                                          "background: qlineargradient(spread:pad, \n"
                                          "x1:0, y1:0, \n"
                                          "x2:0, y2:1, \n"
                                          "stop:0 rgba(0, 0, 0, 0), \n"
                                          "stop:0.3 rgba(0, 0, 0, 30), \n"
                                          "stop:0.6 rgba(0, 0, 0, 90), \n"
                                          "stop:1 rgba(0, 0, 0,150)\n"
                                          ");\n"
                                          "padding-left:10px;\n"
                                          "padding-right:10px;\n"
                                          "\n"
                                          "}")
        self.playControlBar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.playControlBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.playControlBar.setObjectName("playControlBar")
        self.playControlBarLayout_2 = QtWidgets.QVBoxLayout(
            self.playControlBar)
        self.playControlBarLayout_2.setContentsMargins(0, 0, 0, 0)
        self.playControlBarLayout_2.setSpacing(0)
        self.playControlBarLayout_2.setObjectName("playControlBarLayout_2")
        self.seekSliderFrame = QtWidgets.QFrame(self.playControlBar)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.seekSliderFrame.sizePolicy().hasHeightForWidth())
        self.seekSliderFrame.setSizePolicy(sizePolicy)
        self.seekSliderFrame.setMinimumSize(QtCore.QSize(0, 12))
        self.seekSliderFrame.setMaximumSize(QtCore.QSize(16777215, 10))
        self.seekSliderFrame.setStyleSheet("#playProgressFrame{\n"
                                           "margin:0px;\n"
                                           "border:0px;\n"
                                           "padding:0px;\n"
                                           "background: rgba(0,0,0,0);\n"
                                           "}")
        self.seekSliderFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.seekSliderFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.seekSliderFrame.setLineWidth(0)
        self.seekSliderFrame.setObjectName("seekSliderFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.seekSliderFrame)
        self.horizontalLayout.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.seekSlider = SeekSlider(self.seekSliderFrame)
        self.seekSlider.setMaximum(100)
        self.seekSlider.setProperty("value", 0)
        self.seekSlider.setOrientation(QtCore.Qt.Horizontal)
        self.seekSlider.setObjectName("seekSlider")
        self.horizontalLayout.addWidget(self.seekSlider)
        self.playControlBarLayout_2.addWidget(self.seekSliderFrame)
        self.playControlFrame = QtWidgets.QFrame(self.playControlBar)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.playControlFrame.sizePolicy().hasHeightForWidth())
        self.playControlFrame.setSizePolicy(sizePolicy)
        self.playControlFrame.setMinimumSize(QtCore.QSize(0, 90))
        self.playControlFrame.setMaximumSize(QtCore.QSize(16777215, 90))
        self.playControlFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.playControlFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.playControlFrame.setLineWidth(0)
        self.playControlFrame.setObjectName("playControlFrame")
        self.playControlFrameLayout = QtWidgets.QHBoxLayout(
            self.playControlFrame)
        self.playControlFrameLayout.setContentsMargins(0, 0, 0, 0)
        self.playControlFrameLayout.setSpacing(0)
        self.playControlFrameLayout.setObjectName("playControlFrameLayout")
        self.playControlLeftFrame = QtWidgets.QFrame(self.playControlFrame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.playControlLeftFrame.sizePolicy().hasHeightForWidth())
        self.playControlLeftFrame.setSizePolicy(sizePolicy)
        self.playControlLeftFrame.setMinimumSize(QtCore.QSize(0, 90))
        self.playControlLeftFrame.setMaximumSize(QtCore.QSize(16777215, 90))
        self.playControlLeftFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.playControlLeftFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.playControlLeftFrame.setLineWidth(0)
        self.playControlLeftFrame.setObjectName("playControlLeftFrame")
        self.playControlLeftFrameLayout = QtWidgets.QHBoxLayout(
            self.playControlLeftFrame)
        self.playControlLeftFrameLayout.setContentsMargins(20, 0, 20, 0)
        self.playControlLeftFrameLayout.setSpacing(10)
        self.playControlLeftFrameLayout.setObjectName(
            "playControlLeftFrameLayout")
        self.playButton = QtWidgets.QPushButton(self.playControlLeftFrame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.playButton.sizePolicy().hasHeightForWidth())
        self.playButton.setSizePolicy(sizePolicy)
        self.playButton.setMinimumSize(QtCore.QSize(30, 30))
        self.playButton.setMaximumSize(QtCore.QSize(30, 30))
        self.playButton.setStyleSheet("#playButton{\n"
                                      "image: url(:/play_control_icon/pause_btn.svg);\n"
                                      "background-color: rgba(0,0,0,0);\n"
                                      "padding:0;\n"
                                      "border:0;\n"
                                      "margin:0;\n"
                                      "}\n"
                                      "#playButton:checked{\n"
                                      "image: url(:/play_control_icon/play_btn.svg);\n"
                                      "background-color: rgba(0,0,0,0);\n"
                                      "padding:0;\n"
                                      "border:0;\n"
                                      "margin:0;\n"
                                      "}")
        self.playButton.setText("")
        self.playButton.setIconSize(QtCore.QSize(0, 0))
        self.playButton.setCheckable(True)
        self.playButton.setChecked(False)
        self.playButton.setObjectName("playButton")
        self.playControlLeftFrameLayout.addWidget(self.playButton)
        self.playProgressInfo = QtWidgets.QLineEdit(self.playControlLeftFrame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.playProgressInfo.sizePolicy().hasHeightForWidth())
        self.playProgressInfo.setSizePolicy(sizePolicy)
        self.playProgressInfo.setMinimumSize(QtCore.QSize(150, 25))
        self.playProgressInfo.setMaximumSize(QtCore.QSize(150, 25))
        self.playProgressInfo.setStyleSheet("#playProgressInfo{\n"
                                            "background-color: rgba(0,0,0,0);\n"
                                            "color:rgba(255, 255, 255, 230);\n"
                                            "font-family: Microsoft YaHei;\n"
                                            "font-size:18px;\n"
                                            "border:0;\n"
                                            "padding:0;\n"
                                            "margin-left:5px;\n"
                                            "margin-right:5px\n"
                                            "}")
        self.playProgressInfo.setText("")
        self.playProgressInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.playProgressInfo.setDragEnabled(False)
        self.playProgressInfo.setReadOnly(True)
        self.playProgressInfo.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.playProgressInfo.setObjectName("playProgressInfo")
        self.playControlLeftFrameLayout.addWidget(self.playProgressInfo)
        self.playControlFrameLayout.addWidget(self.playControlLeftFrame)
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.playControlFrameLayout.addItem(spacerItem)
        self.playControlRightFrame = QtWidgets.QFrame(self.playControlFrame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.playControlRightFrame.sizePolicy().hasHeightForWidth())
        self.playControlRightFrame.setSizePolicy(sizePolicy)
        self.playControlRightFrame.setMinimumSize(QtCore.QSize(0, 90))
        self.playControlRightFrame.setMaximumSize(QtCore.QSize(16777215, 90))
        self.playControlRightFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.playControlRightFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.playControlRightFrame.setLineWidth(0)
        self.playControlRightFrame.setObjectName("playControlRightFrame")
        self.playControlRightFrameLayout_2 = QtWidgets.QHBoxLayout(
            self.playControlRightFrame)
        self.playControlRightFrameLayout_2.setContentsMargins(20, 0, 20, 0)
        self.playControlRightFrameLayout_2.setSpacing(30)
        self.playControlRightFrameLayout_2.setObjectName(
            "playControlRightFrameLayout_2")
        self.superResolutionButton = QtWidgets.QPushButton(
            self.playControlRightFrame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.superResolutionButton.sizePolicy().hasHeightForWidth())
        self.superResolutionButton.setSizePolicy(sizePolicy)
        self.superResolutionButton.setMinimumSize(QtCore.QSize(0, 30))
        self.superResolutionButton.setMaximumSize(QtCore.QSize(16777215, 30))
        self.superResolutionButton.setStyleSheet("#superResolutionButton{\n"
                                                 "color:rgba(255,255,255,230);\n"
                                                 "font-family: Microsoft YaHei;\n"
                                                 "font-weight:bold;\n"
                                                 "font-size:20px;\n"
                                                 "background-color: rgba(0,0,0,0);\n"
                                                 "padding:0;\n"
                                                 "border:0;\n"
                                                 "margin:0;\n"
                                                 "}")
        self.superResolutionButton.setIconSize(QtCore.QSize(0, 0))
        self.superResolutionButton.setCheckable(True)
        self.superResolutionButton.setObjectName("superResolutionButton")
        self.playControlRightFrameLayout_2.addWidget(
            self.superResolutionButton)
        self.resolutionButton = QtWidgets.QPushButton(
            self.playControlRightFrame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.resolutionButton.sizePolicy().hasHeightForWidth())
        self.resolutionButton.setSizePolicy(sizePolicy)
        self.resolutionButton.setMinimumSize(QtCore.QSize(0, 30))
        self.resolutionButton.setMaximumSize(QtCore.QSize(16777215, 30))
        self.resolutionButton.setStyleSheet("#resolutionButton{\n"
                                            "color:rgba(255,255,255,230);\n"
                                            "font-family: Microsoft YaHei;\n"
                                            "font-weight:bold;\n"
                                            "font-size:20px;\n"
                                            "background-color: rgba(0,0,0,0);\n"
                                            "padding:0;\n"
                                            "border:0;\n"
                                            "margin:0;\n"
                                            "}")
        self.resolutionButton.setCheckable(True)
        self.resolutionButton.setObjectName("resolutionButton")
        self.playControlRightFrameLayout_2.addWidget(self.resolutionButton)
        self.volumeButton = QtWidgets.QPushButton(self.playControlRightFrame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.volumeButton.sizePolicy().hasHeightForWidth())
        self.volumeButton.setSizePolicy(sizePolicy)
        self.volumeButton.setMinimumSize(QtCore.QSize(30, 30))
        self.volumeButton.setMaximumSize(QtCore.QSize(27, 32))
        self.volumeButton.setStyleSheet("#volumeButton{\n"
                                        "image: url(:/play_control_icon/volume_btn.svg);\n"
                                        "background-color: rgba(0,0,0,0);\n"
                                        "padding:0;\n"
                                        "border:0;\n"
                                        "margin:0;\n"
                                        "}\n"
                                        "#volumeButton:checked{\n"
                                        "image: url(:/play_control_icon/mute_btn.svg);\n"
                                        "background-color: rgba(0,0,0,0);\n"
                                        "padding:0;\n"
                                        "border:0;\n"
                                        "margin:0;\n"
                                        "}")
        self.volumeButton.setText("")
        self.volumeButton.setIconSize(QtCore.QSize(0, 0))
        self.volumeButton.setObjectName("volumeButton")
        self.playControlRightFrameLayout_2.addWidget(self.volumeButton)
        self.settingButton = QtWidgets.QPushButton(self.playControlRightFrame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.settingButton.sizePolicy().hasHeightForWidth())
        self.settingButton.setSizePolicy(sizePolicy)
        self.settingButton.setMinimumSize(QtCore.QSize(32, 32))
        self.settingButton.setMaximumSize(QtCore.QSize(32, 32))
        self.settingButton.setStyleSheet("#settingButton{\n"
                                         "image: url(:/play_control_icon/setting_btn.svg);\n"
                                         "background-color: rgba(0,0,0,0);\n"
                                         "padding:0;\n"
                                         "border:0;\n"
                                         "margin:0;\n"
                                         "}")
        self.settingButton.setText("")
        self.settingButton.setIconSize(QtCore.QSize(0, 0))
        self.settingButton.setCheckable(True)
        self.settingButton.setObjectName("settingButton")
        self.playControlRightFrameLayout_2.addWidget(self.settingButton)
        self.fullScreenButton = QtWidgets.QPushButton(
            self.playControlRightFrame)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.fullScreenButton.sizePolicy().hasHeightForWidth())
        self.fullScreenButton.setSizePolicy(sizePolicy)
        self.fullScreenButton.setMinimumSize(QtCore.QSize(30, 30))
        self.fullScreenButton.setMaximumSize(QtCore.QSize(30, 30))
        self.fullScreenButton.setStyleSheet("#fullScreenButton{\n"
                                            "image: url(:/play_control_icon/full_screen_btn.svg);\n"
                                            "background-color: rgba(0,0,0,0);\n"
                                            "padding:0;\n"
                                            "border:0;\n"
                                            "margin:0;\n"
                                            "}\n"
                                            "#fullScreenButton:checked{\n"
                                            "image: url(:/play_control_icon/small_screen_btn.svg);\n"
                                            "background-color: rgba(0,0,0,0);\n"
                                            "padding:0;\n"
                                            "border:0;\n"
                                            "margin:0;\n"
                                            "}")
        self.fullScreenButton.setText("")
        self.fullScreenButton.setIconSize(QtCore.QSize(0, 0))
        self.fullScreenButton.setCheckable(True)
        self.fullScreenButton.setObjectName("fullScreenButton")
        self.playControlRightFrameLayout_2.addWidget(self.fullScreenButton)
        self.playControlRightFrameLayout_2.setStretch(0, 1)
        self.playControlRightFrameLayout_2.setStretch(1, 1)
        self.playControlRightFrameLayout_2.setStretch(2, 1)
        self.playControlRightFrameLayout_2.setStretch(3, 1)
        self.playControlRightFrameLayout_2.setStretch(4, 1)
        self.playControlFrameLayout.addWidget(self.playControlRightFrame)
        self.playControlBarLayout_2.addWidget(self.playControlFrame)
