# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\player\ui\PlayerWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from ..CiliCiliPlayer import CiliCiliPlayer


class Ui_PlayerWindow(object):
    def setupUi(self, PlayerWindow,ciliCiliPlayer):
        PlayerWindow.setObjectName("PlayerWindow")
        PlayerWindow.resize(1189, 767)
        PlayerWindow.setMinimumSize(QtCore.QSize(1050, 560))
        PlayerWindow.setStyleSheet("*{\n"
"background-color:rgba(30, 30, 30, 255);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(PlayerWindow)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TopBar = QtWidgets.QWidget(PlayerWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TopBar.sizePolicy().hasHeightForWidth())
        self.TopBar.setSizePolicy(sizePolicy)
        self.TopBar.setMinimumSize(QtCore.QSize(0, 50))
        self.TopBar.setObjectName("TopBar")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.TopBar)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.WindowOP = QtWidgets.QWidget(self.TopBar)
        self.WindowOP.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.WindowOP.sizePolicy().hasHeightForWidth())
        self.WindowOP.setSizePolicy(sizePolicy)
        self.WindowOP.setMinimumSize(QtCore.QSize(150, 0))
        self.WindowOP.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.WindowOP.setObjectName("WindowOP")
        self.CloseButton = QtWidgets.QPushButton(self.WindowOP)
        self.CloseButton.setGeometry(QtCore.QRect(104, 12, 28, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CloseButton.sizePolicy().hasHeightForWidth())
        self.CloseButton.setSizePolicy(sizePolicy)
        self.CloseButton.setMinimumSize(QtCore.QSize(28, 28))
        self.CloseButton.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.CloseButton.setStyleSheet("#CloseButton {\n"
"image: url(:/window_op/window_op_icon/close.svg);\n"
"background-color: rgba(0, 0, 0, 0);\n"
"padding: 5px,5px;\n"
"border:0;\n"
"margin:0;\n"
"border-radius: 3px;\n"
"}\n"
"\n"
"#CloseButton:hover{\n"
"image: url(:/window_op/window_op_icon/close.svg);\n"
"background-color: rgb(230, 230, 230);\n"
"padding: 5px,5px;\n"
"border:0;\n"
"margin:0;\n"
"border-radius: 3px;\n"
"}")
        self.CloseButton.setInputMethodHints(QtCore.Qt.ImhNone)
        self.CloseButton.setText("")
        self.CloseButton.setIconSize(QtCore.QSize(25, 25))
        self.CloseButton.setAutoDefault(False)
        self.CloseButton.setDefault(False)
        self.CloseButton.setFlat(False)
        self.CloseButton.setObjectName("CloseButton")
        self.MaxButton = QtWidgets.QPushButton(self.WindowOP)
        self.MaxButton.setEnabled(True)
        self.MaxButton.setGeometry(QtCore.QRect(61, 12, 28, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MaxButton.sizePolicy().hasHeightForWidth())
        self.MaxButton.setSizePolicy(sizePolicy)
        self.MaxButton.setMinimumSize(QtCore.QSize(28, 28))
        self.MaxButton.setStyleSheet("#MaxButton {\n"
"image: url(:/window_op/window_op_icon/max.svg);\n"
"background-color: rgba(0, 0, 0, 0);\n"
"padding: 5px,5px;\n"
"border:0;\n"
"margin:0;\n"
"border-radius: 3px;\n"
"}\n"
"\n"
"#MaxButton:hover{\n"
"image: url(:/window_op/window_op_icon/max.svg);\n"
"background-color: rgb(230, 230, 230);\n"
"padding: 5px,5px;\n"
"border:0;\n"
"margin:0;\n"
"border-radius: 3px;\n"
"}")
        self.MaxButton.setText("")
        self.MaxButton.setIconSize(QtCore.QSize(25, 25))
        self.MaxButton.setAutoDefault(False)
        self.MaxButton.setDefault(False)
        self.MaxButton.setFlat(True)
        self.MaxButton.setObjectName("MaxButton")
        self.MinButton = QtWidgets.QPushButton(self.WindowOP)
        self.MinButton.setGeometry(QtCore.QRect(18, 12, 28, 28))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MinButton.sizePolicy().hasHeightForWidth())
        self.MinButton.setSizePolicy(sizePolicy)
        self.MinButton.setMinimumSize(QtCore.QSize(28, 28))
        self.MinButton.setStyleSheet("#MinButton {\n"
"image: url(:/window_op/window_op_icon/min.svg);\n"
"background-color: rgba(0, 0, 0, 0);\n"
"padding: 5px,5px;\n"
"border:0;\n"
"margin:0;\n"
"border-radius: 3px;\n"
"}\n"
"\n"
"#MinButton:hover{\n"
"image: url(:/window_op/window_op_icon/min.svg);\n"
"background-color: rgb(230, 230, 230);\n"
"padding: 5px,5px;\n"
"border:0;\n"
"margin:0;\n"
"border-radius: 3px;\n"
"}")
        self.MinButton.setText("")
        self.MinButton.setIconSize(QtCore.QSize(25, 25))
        self.MinButton.setAutoDefault(False)
        self.MinButton.setDefault(False)
        self.MinButton.setFlat(True)
        self.MinButton.setObjectName("MinButton")
        self.horizontalLayout_3.addWidget(self.WindowOP)
        self.verticalLayout.addWidget(self.TopBar)
        self.Container = QtWidgets.QWidget(PlayerWindow)
        self.Container.setObjectName("Container")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Container)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.CiliCiliPlayer = ciliCiliPlayer
        self.CiliCiliPlayer.setStyleSheet("")
        self.CiliCiliPlayer.setObjectName("CiliCiliPlayer")
        self.horizontalLayout.addWidget(self.CiliCiliPlayer)
        self.InfoContainer = QtWidgets.QWidget(self.Container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InfoContainer.sizePolicy().hasHeightForWidth())
        self.InfoContainer.setSizePolicy(sizePolicy)
        self.InfoContainer.setMinimumSize(QtCore.QSize(350, 0))
        self.InfoContainer.setObjectName("InfoContainer")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.InfoContainer)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.InfoTopBar = QtWidgets.QWidget(self.InfoContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InfoTopBar.sizePolicy().hasHeightForWidth())
        self.InfoTopBar.setSizePolicy(sizePolicy)
        self.InfoTopBar.setMinimumSize(QtCore.QSize(0, 50))
        self.InfoTopBar.setMaximumSize(QtCore.QSize(16777215, 50))
        self.InfoTopBar.setStyleSheet("#InfoTopBar {\n"
"border-bottom-width: 1px;\n"
"border-style: solid;\n"
"border-bottom-color: rgb(40, 40, 40);\n"
"}")
        self.InfoTopBar.setObjectName("InfoTopBar")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.InfoTopBar)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Introduction = QtWidgets.QPushButton(self.InfoTopBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Introduction.sizePolicy().hasHeightForWidth())
        self.Introduction.setSizePolicy(sizePolicy)
        self.Introduction.setMinimumSize(QtCore.QSize(35, 35))
        self.Introduction.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Introduction.setFont(font)
        self.Introduction.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Introduction.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Introduction.setAutoFillBackground(False)
        self.Introduction.setStyleSheet("#Introduction{\n"
"color:rgb(235, 235, 235);\n"
"margin:0;\n"
"padding:0;\n"
"border:0;\n"
"}\n"
"#Introduction:hover{\n"
"color: rgb(251, 114, 153);\n"
"margin:0;\n"
"padding:0;\n"
"border:0;\n"
"\n"
"}")
        self.Introduction.setAutoDefault(False)
        self.Introduction.setDefault(False)
        self.Introduction.setFlat(False)
        self.Introduction.setObjectName("Introduction")
        self.horizontalLayout_4.addWidget(self.Introduction)
        self.Comment = QtWidgets.QPushButton(self.InfoTopBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Comment.sizePolicy().hasHeightForWidth())
        self.Comment.setSizePolicy(sizePolicy)
        self.Comment.setMinimumSize(QtCore.QSize(35, 35))
        self.Comment.setMaximumSize(QtCore.QSize(35, 35))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Comment.setFont(font)
        self.Comment.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Comment.setStyleSheet("#Comment{\n"
"color:rgb(235, 235, 235);\n"
"margin:0;\n"
"padding:0;\n"
"border:0;\n"
"}\n"
"#Comment:hover{\n"
"color: rgb(251, 114, 153);\n"
"margin:0;\n"
"padding:0;\n"
"border:0;\n"
"\n"
"}")
        self.Comment.setFlat(False)
        self.Comment.setObjectName("Comment")
        self.horizontalLayout_4.addWidget(self.Comment)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2.addWidget(self.InfoTopBar)
        self.scrollArea = QtWidgets.QScrollArea(self.InfoContainer)
        self.scrollArea.setStyleSheet("#scrollArea{\n"
"margin:0;\n"
"padding:0;\n"
"}")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 350, 667))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.horizontalLayout.addWidget(self.InfoContainer)
        self.verticalLayout.addWidget(self.Container)

        self.retranslateUi(PlayerWindow)
        QtCore.QMetaObject.connectSlotsByName(PlayerWindow)

    def retranslateUi(self, PlayerWindow):
        _translate = QtCore.QCoreApplication.translate
        PlayerWindow.setWindowTitle(_translate("PlayerWindow", "PlayerWindow"))
        self.Introduction.setText(_translate("PlayerWindow", "简介"))
        self.Comment.setText(_translate("PlayerWindow", "评论"))
from .PlayerAssets import * 
