# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src\player\ui\SeekSlider.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtWidgets,QtGui,QtCore


class SeekSlider(QtWidgets.QSlider):
    def __init__(self,widget):
        super(SeekSlider, self).__init__(widget)
        self.setupUi()

    
    def mousePressEvent(self, event):
        # 获取上面的拉动块位置
        option = QtWidgets.QStyleOptionSlider()
        self.initStyleOption(option)
        rect = self.style().subControlRect(
            QtWidgets.QStyle.CC_Slider, option, QtWidgets.QStyle.SC_SliderHandle, self)
        if rect.contains(event.pos()):
            # 如果鼠标点击的位置在滑块上则交给Qt自行处理
            super(SeekSlider, self).mousePressEvent(event)
            return
        if self.orientation() == QtCore.Qt.Horizontal:
            # 横向，要考虑invertedAppearance是否反向显示的问题
            self.setValue(self.style().sliderValueFromPosition(
                self.minimum(), self.maximum(),
                event.x() if not self.invertedAppearance() else (self.width(
                ) - event.x()), self.width()))
        else:
            # 纵向
            self.setValue(self.style().sliderValueFromPosition(
                self.minimum(), self.maximum(),
                (self.height() - event.y()) if not self.invertedAppearance(
                ) else event.y(), self.height()))

        return super(SeekSlider, self).mousePressEvent(event)

    def setupUi(self,):
        # self.seekSlider.setGeometry(QtCore.QRect(100, 300, 741, 81))
        self.setStyleSheet("\n"
        "\n"
        "/*滑块的样式*/\n"
        "QSlider::groove:horizontal {\n"
        "margin:0 -6 0 -6;\n"
        "padding:0;\n"
        "border:0;\n"
        "\n"
        "background: rgba(200,200,200,70);\n"
        "height: 3px;\n"
        "\n"
        "}\n"
        "\n"
        "QSlider::groove:horizontal:hover {\n"
        "margin:0 -6 0 -6;\n"
        "padding:0;\n"
        "border:0;\n"
        "background: rgba(200,200,200,70);\n"
        "height: 6px;\n"
        "\n"
        "}\n"
        "/*滑块经过的颜色:前面的颜色*/\n"
        "QSlider::sub-page:horizontal {\n"
        "background: rgb(255, 102, 153);\n"
        "margin:0;\n"
        "padding:0;\n"
        "border-radius: 3px;\n"
        "}\n"
        "\n"
        "QSlider::handle:horizontal \n"
        "{\n"
        "    background: rgba(0,0,0,0);\n"
        "    width: 6px;\n"
        "    margin-top: -3px;\n"
        "    margin-bottom: -3px;\n"
        "\n"
        "    padding-left: 3px;\n"
        "    padding-right: 3px;\n"
        "    border-radius: 6px;\n"
        "    border：none;\n"
        "}\n"
        "\n"
        "\n"
        "QSlider::handle:horizontal:hover {\n"
        "    background: rgb(255, 102, 153);\n"
        "    width: 6px;\n"
        "    margin-top: -3px;\n"
        "    margin-bottom: -3px;\n"
        "    padding-left: 3px;\n"
        "    padding-right: 3px;\n"
        "    border-radius: 6px;\n"
        "    border：none;\n"
        "}")
        self.setMaximum(100)
        self.setProperty("value", 0)
        self.setOrientation(QtCore.Qt.Horizontal)
        self.setObjectName("seekSlider")

