# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\main_window\video_card\video_card.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VideoCard(object):
    def setupUi(self, VideoCard):
        VideoCard.setObjectName("VideoCard")
        VideoCard.resize(242, 222)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VideoCard.sizePolicy().hasHeightForWidth())
        VideoCard.setSizePolicy(sizePolicy)
        VideoCard.setMinimumSize(QtCore.QSize(242, 222))
        VideoCard.setStyleSheet("*{\n"
"background-color: rgba(123,123,34,255);\n"
# "background-color: rgba(0,0,0,0);"
"margin:0px;\n"
"padding:0px;\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(VideoCard)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.VideoCover = QtWidgets.QLabel(VideoCard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VideoCover.sizePolicy().hasHeightForWidth())
        self.VideoCover.setSizePolicy(sizePolicy)
        self.VideoCover.setMinimumSize(QtCore.QSize(240, 135))
        self.VideoCover.setSizeIncrement(QtCore.QSize(0, 0))
        self.VideoCover.setBaseSize(QtCore.QSize(0, 0))
        self.VideoCover.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.VideoCover.setMouseTracking(True)
        self.VideoCover.setStyleSheet("#VideoCover{\n"
"background-repeat:no-repeat;\n"
"background-position:center;\n"
"background-origin:border;\n"
"\n"
"}")
        self.VideoCover.setLineWidth(0)
        self.VideoCover.setText("")
        self.VideoCover.setTextFormat(QtCore.Qt.PlainText)
        self.VideoCover.setAlignment(QtCore.Qt.AlignCenter)
        self.VideoCover.setObjectName("VideoCover")
        self.verticalLayout.addWidget(self.VideoCover)
        self.VideoTitle = QtWidgets.QTextEdit(VideoCard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VideoTitle.sizePolicy().hasHeightForWidth())
        self.VideoTitle.setSizePolicy(sizePolicy)
        self.VideoTitle.setMinimumSize(QtCore.QSize(0, 45))
        self.VideoTitle.setMaximumSize(QtCore.QSize(16777215, 45))
        self.VideoTitle.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.VideoTitle.setMouseTracking(True)
        self.VideoTitle.setFocusPolicy(QtCore.Qt.NoFocus)
        self.VideoTitle.setAcceptDrops(False)
        self.VideoTitle.setStyleSheet("#VideoTitle{\n"
"\n"
"}")
        self.VideoTitle.setInputMethodHints(QtCore.Qt.ImhNone)
        self.VideoTitle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.VideoTitle.setUndoRedoEnabled(False)
        self.VideoTitle.setReadOnly(True)
        self.VideoTitle.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.VideoTitle.setObjectName("VideoTitle")
        self.verticalLayout.addWidget(self.VideoTitle)
        self.VideoAuthor = QtWidgets.QLineEdit(VideoCard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VideoAuthor.sizePolicy().hasHeightForWidth())
        self.VideoAuthor.setSizePolicy(sizePolicy)
        self.VideoAuthor.setMinimumSize(QtCore.QSize(0, 20))
        self.VideoAuthor.setMaximumSize(QtCore.QSize(16777215, 20))
        self.VideoAuthor.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.VideoAuthor.setMouseTracking(True)
        self.VideoAuthor.setFocusPolicy(QtCore.Qt.NoFocus)
        self.VideoAuthor.setAcceptDrops(False)
        self.VideoAuthor.setStyleSheet("#VideoAuthor{\n"
"}")
        self.VideoAuthor.setFrame(False)
        self.VideoAuthor.setReadOnly(True)
        self.VideoAuthor.setObjectName("VideoAuthor")
        self.verticalLayout.addWidget(self.VideoAuthor)
        self.PlayInfo = QtWidgets.QLineEdit(VideoCard)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PlayInfo.sizePolicy().hasHeightForWidth())
        self.PlayInfo.setSizePolicy(sizePolicy)
        self.PlayInfo.setMinimumSize(QtCore.QSize(0, 20))
        self.PlayInfo.setMaximumSize(QtCore.QSize(16777215, 20))
        self.PlayInfo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PlayInfo.setFocusPolicy(QtCore.Qt.NoFocus)
        self.PlayInfo.setAcceptDrops(False)
        self.PlayInfo.setStyleSheet("#PlayInfo{\n"
"}")
        self.PlayInfo.setFrame(False)
        self.PlayInfo.setReadOnly(True)
        self.PlayInfo.setObjectName("PlayInfo")
        self.verticalLayout.addWidget(self.PlayInfo)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(VideoCard)
        QtCore.QMetaObject.connectSlotsByName(VideoCard)

    def retranslateUi(self, VideoCard):
        _translate = QtCore.QCoreApplication.translate
        VideoCard.setWindowTitle(_translate("VideoCard", "VideoCard"))
